### ISSUE TITLE
Maybe use cylc.github.io instead of cylc.github.io/cylc ?

### ISSUE THREAD

**Issue by kinow** [cylc/cylc-admin#7]
If we move the `gh-pages` off from the Cylc main repository, to a different repository `cylc/cylc.github.io`, that would be the organisation default site. Serving the URL `https://cylc.github.io`.

It may have a positive impact on the site's SEO, but I think the main advantage would be that it's easier to have one word less. The other site from `gh-pages` could be left there with a redirect to the new site.

**Comment by hjoliver** [comment]
(we should talk about this one...)

**Comment by hjoliver** [comment]
I think we should do this.  It's always been somewhat painful switching to gh-pages in the main repository anyway, as the web site branch is more or less entirely unrelated to the master branch.

**Comment by hjoliver** [comment]
I've done this: https://cylc.github.io/index.html

However, the dynamic site metadata extraction (release versions etc., in the right side-bar) doesn't work online, because the `site` variable (see `_includes/repository.html`) points to the cylc/cylc.github.io instead of cylc/cylc - even though I have set `repository: cylc/cylc` in `_config.yml` ... which does have the desired effect when using jekyll locally (install the right gems, then run `jekyll serve` in my local clone). @kinow - might be something you could look at - I have a VC now...

**Comment by kinow** [comment]
Sure thing, just give me a few minutes...

**Comment by kinow** [comment]
Interesting. It works locally with `jekyll serve`

![image](https://user-images.githubusercontent.com/304786/53530797-ea428e00-3b55-11e9-91ad-1ed44111dc90.png)

**Comment by kinow** [comment]
Even though `_config.yml` contains an entry with `repository: cylc/cylc`, looks like `site.github.releases_url` points to the local repository's releases URL.

![image](https://user-images.githubusercontent.com/304786/53531651-9f764580-3b58-11e9-926d-330967eee9a4.png)

**Comment by hjoliver** [comment]
Yes, that's exactly what I found (but didn't explain very clearly, I guess!).

Not sure there's anything we can do about this, if GitHub pages is just ignoring the relevant config.

**Comment by kinow** [comment]
https://github.com/cylc/cylc.github.io/pull/1

**Comment by hjoliver** [comment]
Done :bouquet:
